# Generated by Django 3.2.9 on 2021-11-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='avatar',
            field=models.ImageField(upload_to='media/paricipants_avatars', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('MAN', 'Man'), ('WOMAN', 'Woman')], max_length=5, verbose_name='Gender'),
        ),
    ]
