# Generated by Django 3.2.9 on 2021-11-13 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_website', '0002_auto_20211112_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='match',
            field=models.ManyToManyField(blank=True, null=True, related_name='_meeting_website_participant_match_+', to=settings.AUTH_USER_MODEL, verbose_name='Match'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='avatar',
            field=models.ImageField(upload_to='partcipants_avatars', verbose_name='Avatar'),
        ),
    ]
