# Generated by Django 3.2.9 on 2021-11-13 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_website', '0004_alter_participant_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='lat',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='participant',
            name='lon',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(18)], verbose_name='Age'),
        ),
    ]
