# Generated by Django 3.2.9 on 2021-11-16 11:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_website', '0005_auto_20211113_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='likes_from_user',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name='You liked'), blank=True, default=list, null=True, size=None),
        ),
    ]
